### ISSUE TITLE
Prediction function missing

### ISSUE THREAD

**Issue by Elmiar0642** [jnez71/kalmaNN#12]
How to predict using the models that has been trained?

**Comment by jnez71** [comment]
Use the [`feedforward`](https://github.com/jnez71/kalmaNN/blob/950c298aa9e77a06a1b8ebe2dbe666a1987bcbe8/kalmann/knn.py#L101-L113) or [`classify`](https://github.com/jnez71/kalmaNN/blob/950c298aa9e77a06a1b8ebe2dbe666a1987bcbe8/kalmann/knn.py#L117-L125) method of the `KNN` class as is done in the [demos](https://github.com/jnez71/kalmaNN/tree/master/demos).
