### ISSUE TITLE
Link broken in Readme.md

### ISSUE THREAD

**Issue by tfjgeorge** [jnez71/kalmaNN#5]
in Readme.md you write `An implementation of chapter two from this text.` but the link is broken.. so I dont know which text you are referring to. Could you possibly give the full reference ? Thanks

**Comment by jnez71** [comment]
Sorry about that. Here are fresh links that work for me.
https://pdfs.semanticscholar.org/8b0a/c702624bd1dc0a58b847a65bc6610c01cc48.pdf
https://www.amazon.com/Kalman-Filtering-Neural-Networks-Haykin/dp/0471369985
